### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by jordanwillis** [gergana007/ColmarAcademy#1]
Let me start off by saying, wow...what an amazing job you did on your project!  Not only is the implementation side fantastic, but the overall look and feel that you created made for a very professional looking site.  I typically leave 4-5 github issues with various recommendations or improvements that cover items such as semantic HTML, DRY CSS, proper HTML structure, optimized use of flexbox and media queries, browser compatibility and accessibility, etc., but after a thorough review of your project, there really isn't much I can add (again...because it's really really good)!

With that said, I did note down a few *very* minor things that I thought I would share with you.

1. When using a anchor element (e.g. `<a>`), you don't need to also include a `role` value of `link`.

https://github.com/gergana007/ColmarAcademy/blob/e445f9a6247eb24dff54ceb6ee1dcee962fd5f68/index.html#L71
https://github.com/gergana007/ColmarAcademy/blob/e445f9a6247eb24dff54ceb6ee1dcee962fd5f68/index.html#L84

`<a>` is actually considered a semantic HTML element because it means that this specific content is a link to something, so additionally adding the role `link` is redundant.  Instead, you would use `role="link"` for non-anchor elements that are behaving as a link (which usually requires JavaScript to provide the link behavior).

2. Correct usage of `role="gridcell"`

https://github.com/gergana007/ColmarAcademy/blob/e445f9a6247eb24dff54ceb6ee1dcee962fd5f68/index.html#L107-L114

I can see why you would use th `gridcell` role in the above example because the resulting style of this block is a grid like component.  In reality, `gridcell` is meant to be used in a `<div>` structure that provides a true grid-like layout to your page or a grid-like component such as a table.  As a result, it's technically not valid to use except inside of a container that has a role of `row`.  Here is more information about that.

https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html

3. CSS color functions.

https://github.com/gergana007/ColmarAcademy/blob/e445f9a6247eb24dff54ceb6ee1dcee962fd5f68/resources/css/style.css#L44-L46

Nice job learning more about and using the new CSS color functions.  They provide a nice way to formulate complex colors without having to explicitly define a hex color value.  In the above example, I noticed that you provided 4 arguments to the `rgb` function instead of 3.  Unfortunately, `rgb` can only accept up to 3 values (one for red, one for green, and another for blue).

I think you probably meant to use the `rgba` function which provides an extra argument for `alpha`, which controls opacity.  So instead of what you have, it would be...

``` css
.transparent {
    color: rgba(61, 61, 61, 0.5);
}
```

That about wraps it up!  Honestly, this is the sort of feedback that I rarely provide for this project because students rarely go about and beyond the standard HTML/CSS and include ARIA accessibility and advanced CSS.

With all that said, you earned an "Extremely Exceeds Expectations" on this one.  So keep up the great work!!

**Comment by gergana007** [comment]
Thank you for your feedback! I was not at all familiar with ARIA tags until this course, so I appreciate the feedback.  And thanks for taking over the review.
